apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h5sd1k28m-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h5sd1k28m-java-quarkus-gitops